site_name: squadro
site_url: https://squadro.readthedocs.io/en/latest/
repo_url: https://github.com/MartinBraquet/squadro
edit_uri: https://github.com/MartinBraquet/squadro/blob/main/docs/
site_description: Squadro
site_author: Martin Braquet

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Introduction: index.md
  - Details:
      - details.md
extra:
  version: "2.0.21"
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
